### ISSUE TITLE
Enhancing static page generation speed?

### ISSUE THREAD

**Issue by chunlaw** [sPavl0v/react-spa-prenderer#1]
I am working on a project of a Hong Kong Bus ETA application ([hkbus.app](https://hkbus.app/en)). The package works really well while generating all the pages (~4000 pages) takes quite a long time. Is there any chance to optimize the generating time?

P.S. Instead of switching to other frameworks such as Gatsby or React-static, your work does save a lot of development time for me.

**Comment by chunlaw** [comment]
For your reference, my spa will download a route data file (in JSON) and save it into localstorage for caching. My wild guess is `react-spa-prenderer` does not use localstorage and keep on downloading the data file again and again.

Would it be any code could be insert into the code and notify the app is being pre-rendering? Then I could load an offline data file to boost the performance.

**Comment by sPavl0v** [comment]
Hello @chunlaw, thanks a lot for your feedback, glad to hear that.

Yeah, rendering the page is time consuming and for large amount of pages can take a a bit long.
I would definitely investigate this question and will be looking into adding performance optimization(or maybe just performance mode) in upcoming releases.

**Comment by chunlaw** [comment]
I have done some work for [performance optimization](https://github.com/hkbus/hk-independent-bus-eta/blob/master/src/pre-rendering.js#L86-L101) based on your great ground work.

The major idea of my optimization is to simulate browsing rather than launching the browser and calling the expensive "page.goto". The performance is then optimized from ~3s to ~0.15s per page, and the idea itself also encourages me to improve my app's response time.

However, while the simulation is application-dependent, there might not be an easy way to generalize a package. Anyway, you save me from migrating the project framework like Gatsby. Thanks in advance.

Cheers!!
