### ISSUE TITLE
Building in amplify pipeline build times out

### ISSUE THREAD

**Issue by bioxcode** [sPavl0v/react-spa-prenderer#13]
When running locally this package seems to be working fine, however when pushed and built through AWS amplify, pipeline times out with no feedback. Do you know why it could be taking so long or not completing entirely?

**Comment by sPavl0v** [comment]
Hi @bioxcode, rendering pages can take a while, especially it there are a lot of them. Please consider those facts along with machine capacities or pipeline timeout configs when trying to figure out the way that will work for you.
