### ISSUE TITLE
Puppeteer version upgrade?

### ISSUE THREAD

**Issue by gergelyszabo94** [sPavl0v/react-spa-prenderer#20]
Hello, I just migrated to this from react-snap because I thought it's better maintaned.
It works fine on my Windows machine but I believe the no longer supported puppeteer version is breaking my build on Linux.
Are there any plans to upgrade? We are at 10.4.0, the latest is at 19.2.2.

**Comment by sPavl0v** [comment]
Hi @gergelyszabo94, thanks for mentioning it, i'm going to ship out new version soon, it will contain deps updates.

**Comment by gergelyszabo94** [comment]
Thanks, I did end up making it work though, so my problem was probably not related. I am closing the issue.
