### ISSUE TITLE
index.html build error

### ISSUE THREAD

**Issue by satoshi-soya** [sPavl0v/react-spa-prenderer#3]
On line 52, route ==='/'?'Index': route;
Will build / into /buildindex.html, and expect /build/index.html.
Do you need to change the above code 'index' to '/index'？

**Comment by sPavl0v** [comment]
Hi @satoshi-soya, thanks for catching that!
It looks like script creates redundant buildindex.html file in root directory along with index.htnl file in build directory. I will launch the fix in the new version, it should come in next 2-3 days.

**Comment by satoshi-soya** [comment]
Ok thanks, awesome

**Comment by sPavl0v** [comment]
The fix available in version 1.0.11
